context:
  cache: true
  strict: false
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
gleaner:
  mill: true
  runid: runX
  summon: true
summoner:
    after: ""
    delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
    # will headless, the name of the container "service" work
    headless: http://headless:9222
    #headless: http://localhost:9222
    mode: full
    threads: 5
millers:
  graph: true
minio:
  address:
  port:
  ssl:
  accessKey:
  secretKey:
  bucket:
sources:
  - sourcetype: sitemap
    name: geocodes_demo_datasets
    logo: ""
    url: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
    headless: false
    pid: https://github.com/earthcube/GeoCODES-Metadata/metadata/OtherResources
    propername: Geocodes Demo Datasets
    domain: https://www.earthcube.org/datasets/
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - sourcetype: sitemap
    name: geocodes_examples
    logo: ""
    url: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
    headless: false
    pid: https://github.com/earthcube/GeoCODES-Metadata/
    propername: GeoCodes Tools Examples
    domain: https://github.com/earthcube/GeoCODES-Metadata/
    active: true
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifierstring
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json


## HEADLESS EXAMPLE
  - sourcetype: sitemap
    name: magic
    logo: http://mbobak.ncsa.illinois.edu/ext/ec/magic/MagIC.png
    url: https://www2.earthref.org/MagIC/contributions.sitemap.xml
    headless: true
    pid: http://www.re3data.org/repository/r3d100011910
    propername: Magnetics Information Consortium (MagIC)
    domain: https://www.earthref.org/MagIC
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: $.sameAs
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json

