- ? ''
  : ''
  Active: true
  Domain: https://opentopography.org/sites/opentopography.org/files/ot_transp_logo_2.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: opentopography
  PID: ''
  ProperName: OpenTopography
  SourceType: sitemap
  URL: https://portal.opentopography.org/sitemap.xml
  hack: '3'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://ds.iris.edu/static/img/layout/logos/iris_logo_shadow.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: 'No distribution '
  NOTE: ''
  Name: iris
  PID: Schema Markup Validator
  ProperName: IRIS
  SourceType: sitemap
  URL: http://ds.iris.edu/files/sitemap.xml
  hack: '5'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://portal.edirepository.org/nis/images/EDI-logo-300DPI_5.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: edi
  PID: ''
  ProperName: Environmental Data Initiative
  SourceType: sitemap
  URL: https://portal.edirepository.org/sitemap_index.xml
  hack: '7'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.hydroshare.org/static/img/logo-lg.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: hydroshare
  PID: ''
  ProperName: Consortium of Universities for the Advancement of Hydrologic Science,
    Inc. (CUAHSI)
  SourceType: sitemap
  URL: https://www.hydroshare.org/sitemap-resources.xml
  hack: '11'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.iedadata.org/wp-content/themes/IEDA/assets/img/logo.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: iedadata
  PID: ''
  ProperName: IEDA (Integrated Earth Data Applications)
  SourceType: sitemap
  URL: http://get.iedadata.org/doi/xml-sitemap.php
  hack: '13'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://opentopography.org/sites/opentopography.org/files/ot_transp_logo_2.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: opentopography
  PID: ''
  ProperName: OpenTopography
  SourceType: sitemap
  URL: https://opentopography.org/sitemap.xml
  hack: '15'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.unavco.org/lib/images/banner/uv-logo.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: Schema.org validator says not found... not sure why. looks ok
  NOTE: ''
  Name: unavco
  PID: view-source:https://www.unavco.org/data/doi/10.7283/3S4E-5X54
  ProperName: UNAVCO
  SourceType: sitemap
  URL: https://www.unavco.org/data/doi/sitemap.xml
  hack: '17'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://ssdb.iodp.org/images/head_logo_PRO.gif
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: distribution is misspelled. request for update sent to contact web page https://ssdb.iodp.org/contact.php  2022-11-15
  NOTE: ''
  Name: ssdb.iodp
  PID: Schema Markup Validator
  ProperName: IODP Site Survey Databank
  SourceType: sitemap
  URL: https://ssdb.iodp.org/dataset/sitemap.xml
  hack: '19'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://wiki.linked.earth/wiki/images/thumb/5/51/EarthLinked_Banner_blue_NoShadow.jpg/440px-EarthLinked_Banner_blue_NoShadow.jpg
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: Lots of properties. Possible Cruft
  NOTE: ''
  Name: linked.earth
  PID: Schema Markup Validator
  ProperName: Linked Earth
  SourceType: sitemap
  URL: http://wiki.linked.earth/sitemap.xml
  hack: '23'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: ''
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: lipdverse
  PID: ''
  ProperName: Linked PaleoData
  SourceType: sitemap
  URL: https://lipdverse.org/sitemap.xml
  hack: '25'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://ds.iris.edu/static/img/layout/logos/iris_logo_shadow.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: iris
  PID: ''
  ProperName: IRIS
  SourceType: sitemap
  URL: http://ds.iris.edu/files/sitemap.xml
  hack: '27'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://mbobak.ncsa.illinois.edu/ext/ec/magic/MagIC.png
  Headless: true
  HeadlessWait: '0'
  IdentifierPath: $.sameAs
  IdentifierType: identifiersha
  Logo: Bad Context. Now fixed by gleaner.
  NOTE: ''
  Name: magic
  PID: https://validator.schema.org/#url=https%3A%2F%2Fdx.doi.org%2F10.7288%2FV4%2FMAGIC%2F15607
  ProperName: Magnetics Information Consortium (MagIC)
  SourceType: sitemap
  URL: https://www2.earthref.org/MagIC/contributions.sitemap.xml
  hack: '33'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: http://www.earthchem.org/sites/default/files/files/EC_0-1.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: $.sameAs
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: earthchem
  PID: ''
  ProperName: earthchem
  SourceType: sitemap
  URL: https://ecl.earthchem.org/sitemap.xml
  hack: '37'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.neonscience.org/themes/custom/neon/logo.svg
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: neon
  PID: ''
  ProperName: National Ecological Observatory Network (NEON)
  SourceType: sitemap
  URL: https://geodex.org/neon_prodcodes_sm.xml
  hack: '41'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: ''
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: 'No Distribution or URL to download a dataset: see validator. Many Ancillary
    items '
  NOTE: ''
  Name: designsafe
  PID: Schema Markup Validator
  ProperName: ''
  SourceType: sitemap
  URL: 'https://www.designsafe-ci.org/sitemap.xml '
  hack: '49'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.rvdata.us/images/Logo.4b1519be.png
  Headless: true
  HeadlessWait: '5'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: 'In validator: script jsonld for the dataset is outside of the HTML tag. basically
    it''s own element. In borwserHeadles wait so that dataset JSONLD can be retrieved.
    Two JSONLD, only one item store due to file naming issue (aka sha).  issue: https://github.com/gleanerio/gleaner/issues/111'
  NOTE: ''
  Name: r2r
  PID: Schema Markup Validator
  ProperName: Rolling Deck to Repository Program (R2R)
  SourceType: sitemap
  URL: https://service-dev.rvdata.us/api/sitemap/
  hack: '57'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: ''
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: geocodes_demo_datasets
  PID: ''
  ProperName: Geocodes Demo Datasets
  SourceType: sitemap
  URL: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
  hack: '58'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://www.usap-dc.org/
  Headless: true
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: 'Looks good. Two JSONLD items: possible issue: https://github.com/gleanerio/gleaner/issues/111'
  NOTE: ''
  Name: usap-dc
  PID: Schema Markup Validator
  ProperName: U.S. Antarctic Program Data Center
  SourceType: sitemap
  URL: https://www.usap-dc.org/view/dataset/sitemap.xml
  hack: '59'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://cchdo.ucsd.edu/static/svg/logo_cchdo.svg
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: Using datacatalog with datasets... UI Code, or gleaner needs to handle this
  NOTE: ''
  Name: cchdo
  PID: Schema Markup Validator
  ProperName: CLIVAR and Carbon Hydrographic Data Office
  SourceType: sitemap
  URL: https://cchdo.ucsd.edu/sitemap.xml
  hack: '61'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://amgeo.colorado.edu/static/img/amgeosmall.svg
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: five records
  NOTE: ''
  Name: amgeo
  PID: ''
  ProperName: Assimilative Mapping of Geospace Observations
  SourceType: sitemap
  URL: https://amgeo-dev.colorado.edu/sitemap.xml
  hack: '62'
  validator link: ''
- ? ''
  : ''
  Active: true
  Domain: https://wifire-data.sdsc.edu/uploads/admin/2021-04-22-203649.712143WIFIRECOMMONSSMRES12.png
  Headless: false
  HeadlessWait: '0'
  IdentifierPath: ''
  IdentifierType: identifiersha
  Logo: ''
  NOTE: ''
  Name: wifire
  PID: ''
  ProperName: WIFIRE Commons
  SourceType: sitemap
  URL: https://wifire-data.sdsc.edu/sitemap.xml
  hack: '63'
  validator link: ''
