version: "3.9"
# this NEEDS
# $HOST
# $PROJECT


# not sure is a named external network works well with traffik, or if the label
#            - "traefik.docker.network=traefik_proxy"
# is even needed if the network is defined.

# secrets not working... these become files, so not really working
networks:
  traefik_proxy:
    external: true
  dagster_host:
    driver: overlay
    name: dagster-${PROJECT}
    attachable: true
volumes:
  dagster-postgres:
        driver: local
#  dagster-project:
#    external: true
#    name: dagster-${PROJECT}
# external so it could be shared accross docker swarms
secrets:
  MINIO_ROOT_ACCESS_KEY:
    external: true
  MINIO_ROOT_SECRET_KEY:
    external: true
services:
    dagster-dagit:
        image: docker.io/nsfearthcube/dagster-${PROJECT}:sha-4d94ff8

        secrets:
          - MINIO_ROOT_ACCESS_KEY
          - MINIO_ROOT_SECRET_KEY
        environment:
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - PORTAINER_URL=${PORTAINER_URL}
            - PORTAINER_KEY=${PORTAINER_KEY}
            - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
            - GLEANERIO_GLEANER_ARCHIVE_OBJECT=${GLEANERIO_GLEANER_ARCHIVE_OBJECT}
            - GLEANERIO_GLEANER_ARCHIVE_PATH=${GLEANERIO_GLEANER_ARCHIVE_PATH}
            - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
            - GLEANERIO_NABU_ARCHIVE_OBJECT=${GLEANERIO_NABU_ARCHIVE_OBJECT}
            - GLEANERIO_NABU_ARCHIVE_PATH=${GLEANERIO_NABU_ARCHIVE_PATH}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
            - GLEANER_MINIO_URL=${GLEANER_MINIO_URL}
            - GLEANER_MINIO_PORT=${GLEANER_MINIO_PORT}
            - GLEANER_MINIO_SSL=${GLEANER_MINIO_SSL}
            - GLEANER_MINIO_BUCKET=${GLEANER_MINIO_BUCKET}
            - GLEANER_MINIO_KEY=${GLEANER_MINIO_KEY}
            - GLEANER_MINIO_SECRET=${GLEANER_MINIO_SECRET}
#            - GLEANER_MINIO_KEY=/run/secrets/MINIO_ROOT_ACCESS_KEY
#            - GLEANER_MINIO_SECRET=/run/secrets/MINIO_ROOT_SECRET_KEY
            - GLEANER_BASE=${GLEANER_BASE}
            - GLEANER_OBJECTS=${GLEANER_OBJECTS}
            - GLEANER_MEILI=${GLEANER_MEILI}
            - GLEANER_GRAPH=${GLEANER_GRAPH}
            - GLEANER_GRAPH_CONF=${GLEANER_GRAPH_CONF}
            - GLEANER_TRAEFIK=${GLEANER_TRAEFIK}
            - GLEANER_DOMAIN=${GLEANER_DOMAIN}
            - GLEANER_OSS_DOMAIN=${GLEANER_OSS_DOMAIN}
            - GLEANER_GRAPH_DOMAIN=${GLEANER_GRAPH_DOMAIN}
            - GLEANER_WEB_DOMAIN=${GLEANER_WEB_DOMAIN}
            - GLEANER_WEB2_DOMAIN=${GLEANER_WEB2_DOMAIN}
            - GLEANER_INDEX_DOMAIN=${GLEANER_INDEX_DOMAIN}
            - GLEANER_ADMIN_DOMAIN=${GLEANER_ADMIN_DOMAIN}
        ports:
            - 3000:3000
        networks:
          - traefik_proxy
          - dagster_host
        depends_on:
            - dagster-postgres
        labels:
              - "traefik.enable=true"
              - "traefik.http.routers.sched-${PROJECT}.entrypoints=http"
              - "traefik.http.routers.sched-${PROJECT}.priority=13"
              - "traefik.http.routers.sched-${PROJECT}.rule=Host(`sched.${HOST}`)"
              - "traefik.http.middlewares.sched-https-redirect.redirectscheme.scheme=https"
              - "traefik.http.routers.sched-${PROJECT}.middlewares=sched-https-redirect"
              - "traefik.http.routers.sched-${PROJECT}-secure.entrypoints=https"
              - "traefik.http.routers.sched-${PROJECT}-secure.priority=12"
              - "traefik.http.routers.sched-${PROJECT}-secure.rule=Host(`sched.${HOST}`)"
              - "traefik.http.routers.sched-${PROJECT}-secure.tls=true"
              - "traefik.http.routers.sched-${PROJECT}-secure.tls.certresolver=httpresolver"
              - "traefik.http.routers.sched-${PROJECT}-secure.service=sched-${PROJECT}"
              - "traefik.http.services.sched-${PROJECT}.loadbalancer.server.port=3000"
              - "traefik.docker.network=traefik_proxy"
              - "traefik.http.middlewares.sched-${PROJECT}.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
              - "traefik.http.middlewares.sched-${PROJECT}.headers.accesscontrolalloworigin=*"
              - "traefik.http.middlewares.sched-${PROJECT}.headers.accesscontrolmaxage=100"
              - "traefik.http.middlewares.sched-${PROJECT}.headers.addvaryheader=true"
    dagster-daemon:
        image: docker.io/nsfearthcube/dagster-${PROJECT}:sha-4d94ff8



        secrets:
          - MINIO_ROOT_ACCESS_KEY
          - MINIO_ROOT_SECRET_KEY
        environment:
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - PORTAINER_URL=${PORTAINER_URL}
            - PORTAINER_KEY=${PORTAINER_KEY}
            - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
            - GLEANERIO_GLEANER_ARCHIVE_OBJECT=${GLEANERIO_GLEANER_ARCHIVE_OBJECT}
            - GLEANERIO_GLEANER_ARCHIVE_PATH=${GLEANERIO_GLEANER_ARCHIVE_PATH}
            - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
            - GLEANERIO_NABU_ARCHIVE_OBJECT=${GLEANERIO_NABU_ARCHIVE_OBJECT}
            - GLEANERIO_NABU_ARCHIVE_PATH=${GLEANERIO_NABU_ARCHIVE_PATH}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
            - GLEANER_MINIO_URL=${GLEANER_MINIO_URL}
            - GLEANER_MINIO_PORT=${GLEANER_MINIO_PORT}
            - GLEANER_MINIO_SSL=${GLEANER_MINIO_SSL}
            - GLEANER_MINIO_BUCKET=${GLEANER_MINIO_BUCKET}
            - GLEANER_MINIO_KEY=${GLEANER_MINIO_KEY}
            - GLEANER_MINIO_SECRET=${GLEANER_MINIO_SECRET}
#            - GLEANER_MINIO_KEY=/run/secrets/MINIO_ROOT_ACCESS_KEY
#            - GLEANER_MINIO_SECRET=/run/secrets/MINIO_ROOT_SECRET_KEY
            - GLEANER_BASE=${GLEANER_BASE}
            - GLEANER_OBJECTS=${GLEANER_OBJECTS}
            - GLEANER_MEILI=${GLEANER_MEILI}
            - GLEANER_GRAPH=${GLEANER_GRAPH}
            - GLEANER_GRAPH_CONF=${GLEANER_GRAPH_CONF}
            - GLEANER_TRAEFIK=${GLEANER_TRAEFIK}
            - GLEANER_DOMAIN=${GLEANER_DOMAIN}
            - GLEANER_OSS_DOMAIN=${GLEANER_OSS_DOMAIN}
            - GLEANER_GRAPH_DOMAIN=${GLEANER_GRAPH_DOMAIN}
            - GLEANER_WEB_DOMAIN=${GLEANER_WEB_DOMAIN}
            - GLEANER_WEB2_DOMAIN=${GLEANER_WEB2_DOMAIN}
            - GLEANER_INDEX_DOMAIN=${GLEANER_INDEX_DOMAIN}
            - GLEANER_ADMIN_DOMAIN=${GLEANER_ADMIN_DOMAIN}
        command: "dagster-daemon run"
        depends_on:
            - dagster-postgres
        networks:
            - dagster_host
    dagster-postgres:
        image: postgres:13.3
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - dagster-postgres:/var/lib/postgresql/data
        networks:
           - dagster_host
    headless:
      image: chromedp/headless-shell:latest
  #    build:
  #      context: .
  #      shm_size: "2gb"
      restart: unless-stopped
      shm_size: "2gb"
      labels:
        - "traefik.backend=headlesschrome"
        - "traefik.port=9222"
      ports:
        - 9222:9222
      environment:
        - SERVICE_PORTS=9222
      networks:
        - dagster_host

