version: "3.9"

# networks: production uses traefik_proxy, buth
#  this is local testing
# this includes the ECRR workflows


volumes:

  dagster-storage:
    driver: local
#####
# NOTE
# THERE ARE NO ECO/PROJECT PREFIXES.
#   LOCAL YOU RUN A WITH JUST GLEANERIO_ for one service....
#
###

# DO NOT START IN PYCHARM (unless you set the env variables in your runconfig
# USE:
# ./docker_localstart.sh
services:

## GRPC servers are not just serving the code
# they need to compile it, so same image for all dagster-*
    dagster-code-eco-ecrr:

        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_code
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
       #image: dagster-${PROJECT:-eco}:latest
        image: dagster-gleanerio-local:latest

        environment: &env
            - DEBUG_CONTAINER=${DEBUG_CONTAINER:-false}
            - GLEANERIO_CONFIG_PATH=${GLEANERIO_CONFIG_PATH:-scheduler/configs/test/}
            - GLEANERIO_DAGSTER_CONFIG_PATH=${GLEANERIO_DAGSTER_CONFIG_PATH:-scheduler/logs/}
            - GLEANERIO_DOCKER_CONTAINER_WAIT_TIMEOUT=${GLEANERIO_DOCKER_CONTAINER_WAIT_TIMEOUT:-300}
            - GLEANERIO_DOCKER_GLEANER_CONFIG=${GELANERIO_DOCKER_GLEANER_CONFIG:-gleaner}
            - GLEANERIO_DOCKER_HEADLESS_NETWORK=${GLEANERIO_DOCKER_HEADLESS_NETWORK}
            - GLEANERIO_DOCKER_NABU_CONFIG=${GELANERIO_DOCKER_NABU_CONFIG:-nabu}
            - GLEANERIO_DOCKER_URL=${GELANERIO_DOCKER_URL}
            - GLEANERIO_DOCKER_WORKSPACE_CONFIG=${GELANERIO_DOCKER_WORKSPACE_CONFIG}
            - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
            - GLEANERIO_GLEANER_IMAGE=${GELANERIO_GLEANER_IMAGE}
            - GLEANERIO_GRAPH_NAMESPACE=${GELANERIO_GRAPH_NAMESPACE}
            - GLEANERIO_GRAPH_SUMMARIZE=${GELANERIO_GRAPH_SUMMARIZE:-false}
            - GLEANERIO_GRAPH_SUMMARY_ENDPOINT=${GELANERIO_GRAPH_SUMMARY_ENDPOINT:-${GLEANERIO_GRAPH_URL}}
            - GLEANERIO_GRAPH_SUMMARY_NAMESPACE=${GELANERIO_GRAPH_SUMMARY_NAMESPACE}
            - GLEANERIO_GRAPH_URL=${GELANERIO_GRAPH_URL}
            - GLEANERIO_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX:-scheduler/logs/}
            - GLEANERIO_MINIO_ACCESS_KEY=${GELANERIO_MINIO_ACCESS_KEY}
            - GLEANERIO_MINIO_ADDRESS=${GELANERIO_MINIO_ADDRESS}
            - GLEANERIO_MINIO_BUCKET=${GELANERIO_MINIO_BUCKET}
            - GLEANERIO_MINIO_PORT=${GELANERIO_MINIO_PORT}
            - GLEANERIO_MINIO_SECRET_KEY=${GELANERIO_MINIO_SECRET_KEY}
            - GLEANERIO_MINIO_USE_SSL=${GELANERIO_MINIO_USE_SSL}
            - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
            - GLEANERIO_NABU_IMAGE=${GELANERIO_NABU_IMAGE}
            - GLEANERIO_PORTAINER_APIKEY=${GELANERIO_PORTAINER_APIKEY}
            - GLEANERIO_DEFAULT_SCHEDULE=${GELANERIO_DEFAULT_SCHEDULE:-@weekly}
            - GLEANERIO_DEFAULT_SCHEDULE_TIMEZONE=${ECODEFAULT_SCHEDULE_TIMEZONE:-"America/Los_Angeles"}
            - GLEANERIO_SOURCES_FILENAME=${GELANERIO_SOURCES_FILENAME:-gleanerconfig.yaml}
            - GLEANERIO_TENANT_FILENAME=${GELANERIO_TENANT_FILENAME:-tenant.yaml}
            - GLEANERIO_WORKSPACE_CONFIG_PATH=${GLEANERIO_WORKSPACE_CONFIG_PATH}
            - ECRR_MINIO_BUCKET=${ECRR_MINIO_BUCKET}
            - ECRR_GRAPH_NAMESPACE=${ECRR_GRAPH_NAMESPACE}
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - SLACK_CHANNEL=${GELANERIO_SLACK_CHANNEL:-"#twitterfeed"}
            - SLACK_TOKEN=${GELANERIO_SLACK_TOKEN}
        command:
        - "dagster"
        - "api"
        - "grpc"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "4000"
        - "-m"
        - "workflows.ecrr.ecrr"
        - "-d"
        - "/usr/src/app/"

        volumes: &vol
          - ../deployment/dagster.yaml:/usr/src/app/dagster.yaml
 #         - ../generatedCode/implnet-${PROJECT:-eco}/output/:/usr/src/app/project/${PROJECT:-eco}
          - ../workflows/:/usr/src/app/workflows
        depends_on:
            - dagster-postgres
        networks:
            - traefik_proxy

