context:
  cache: true
  strict: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "./assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "./assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
gleaner:
  mill: true
  runid: runX
  summon: true
summoner:
  after: ""
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
  headless: http://localhost:9222
  mode: full
  threads: 5
millers:
  graph: true
minio:
  address:
  port:
  ssl:
  accessKey:
  secretKey:
  bucket:
sources:
- name: arecibo
  propername: Arecibo Observatory
  url: https://www.naic.edu/ao/landing/sitemap.xml
  sourcetype: sitemap
- name: aws
  propername: AWS OpenData
  url: https://aws.amazon.com/opendata/sitemap.xml
  sourcetype: sitemap
- name: cyvers
  propername: Cyverse
  url: https://cyverse.org/sitemap.xml
  sourcetype: sitemap
- name: drp
  propername: Digital Rock Portal
  url: https://www.digitalrocksportal.org/sitemap.xml
  sourcetype: sitemap
- name: dryad
  propername: Dryad
  url: https://datadryad.org/sitemap.xml
  sourcetype: sitemap
- name: matcommons
  propername: Material Commons
  url: https://materialscommons.org/sitemap.xml
  sourcetype: sitemap
- name: mdf
  propername: Material Data Facility
  url: https://materialsdatafacility.org/sitemap.xml
  sourcetype: sitemap
- name: neon
  propername: Neon Science
  url: https://www.neonscience.org/sitemap.xml
  sourcetype: sitemap
- name: abacus
  propername: Dataverse Abacus
  url: http://abacus.library.ubc.ca/sitemap.xml
  sourcetype: sitemap
- name: acss
  propername: Dataverse Arab Council for the Social Scienes (ACSS)
  url: http://dataverse.theacss.org/sitemap.xml
  sourcetype: sitemap
- name: adf
  propername: Arca Dados Fiocrus - Dataverse
  url: http://dadosdepesquisa.fiocruz.br/sitemap.xml
  sourcetype: sitemap
- name: asulrdr
  propername: Arizona State University (ASU) Library Research Data Repository - Dataverse
  url: http://dataverse.asu.edu/sitemap.xml
  sourcetype: sitemap
- name: aussda
  propername: Austrian Social Science Data Archive (AUSSDA) - Dataverse
  url: http://data.aussda.at/sitemap.xml
  sourcetype: sitemap
- name: borealis
  propername: Borealis - Dataverse
  url: http://borealisdata.ca/sitemap.xml
  sourcetype: sitemap
- name: cifor
  propername: Center for International Forestry Research (CIFOR) - Dataverse
  url: http://data.cifor.org/sitemap.xml
  sourcetype: sitemap
- name: cimmyt
  propername: International Maize and Wheat Improvement Center (CIMMYT) - Dataverse
  url: http://data.cimmyt.org/sitemap.xml
  sourcetype: sitemap
- name: cora
  propername: Catalan Open Research Data (CORA) - Dataverse
  url: http://dataverse.csuc.cat/sitemap.xml
  sourcetype: sitemap
- name: crossda
  propername: Croatian Social Science Data Archive (CROSSDA) - Dataverse
  url: http://data.crossda.hr/sitemap.xml
  sourcetype: sitemap
- name: cuhk
  propername: The Chinese University of Hong Kong Library Research Data Repository (CUHK) - Dataverse
  url: http://researchdata.cuhk.edu.hk/sitemap.xml
  sourcetype: sitemap
- name: tdi
  propername: Dartmouth Institute for Health Policy and Clinical Practice (TDI) - Dataverse
  url: http://dataverse.dartmouth.edu/sitemap.xml
  sourcetype: sitemap
- name: darus
  propername: Data Repository University of Stuttgart (DaRUS) - Dataverse
  url: http://darus.uni-stuttgart.de/sitemap.xml
  sourcetype: sitemap
- name: irs
  propername: DataSuds Institut de recherche pour le développement (IRS) - Dataverse
  url: http://dataverse.ird.fr/sitemap.xml
  sourcetype: sitemap
- name: sceincespo
  propername: SceincesPo - Dataverse
  url: https://data.sciencespo.fr/sitemap.xml
  sourcetype: sitemap
- name: edatos
  propername: Edatos - Dataverse
  url: http://edatos.consorciomadrono.es/sitemap.xml
  sourcetype: sitemap
- name: netherland
  propername: Netherland - Dataverse
  url: http://dataverse.nl/sitemap.xml
  sourcetype: sitemap
- name: norway
  propername: Norway - Dataverse
  url: http://dataverse.no/sitemap.xml
  sourcetype: sitemap
- name: ntu
  propername: Nanyang Technological University Singapore (NTU) - Dataverse
  url: http://researchdata.ntu.edu.sg/sitemap.xml
  sourcetype: sitemap
- name: fiu
  propername: Florida International University (FIU) Research Data Portal - Dataverse
  url: http://dataverse.fiu.edu/sitemap.xml
  sourcetype: sitemap
- name: gro
  propername: Gottingen Research Online - Dataverse
  url: http://data.goettingen-research-online.de/sitemap.xml
  sourcetype: sitemap
- name: harvard
  propername: University of Harvard - Dataverse
  url: http://dataverse.harvard.edu/sitemap.xml
  sourcetype: sitemap
- name: hord
  propername: Heidelberg Open Research Data - Dataverse
  url: http://heidata.uni-heidelberg.de/sitemap.xml
  sourcetype: sitemap
- name: ibict
  propername: Instituto Brasileiro de Informação em Ciencia e Tecnologia (IBICT) - Dataverse
  url: http://repositoriopesquisas.ibict.br/sitemap.xml
  sourcetype: sitemap
- name: icrisat
  propername: Science of discovery to science of delivery (ICRISAT) - Dataverse
  url: http://dataverse.icrisat.org/sitemap.xml
  sourcetype: sitemap
- name: ifdc
  propername: International Fertilizer Development Center (IFDC) - Dataverse
  url: http://dataverse.ifdc.org/sitemap.xml
  sourcetype: sitemap
- name: ifsttar
  propername: French Institute of Science and Technology for Transport, Development and Networks (IFSTTAR) -m Dataverse
  url: http://research-data.ifsttar.fr/sitemap.xml
  sourcetype: sitemap
- name: iisg
  propername: International Institute of Social History (IISG) - Dataverse
  url: http://datasets.iisg.amsterdam/sitemap.xml
  sourcetype: sitemap
- name: irl
  propername: Institute of Russian Literature - Dataverse
  url: http://dataverse.pushdom.ru/sitemap.xml
  sourcetype: sitemap
- name: ipc
  propername: International Potato Center - Dataverse
  url: http://data.cipotato.org/sitemap.xml
  sourcetype: sitemap
- name: iit
  propername: Italian Institute of Technology (IIT) - Dataverse
  url: http://dataverse.iit.it/sitemap.xml
  sourcetype: sitemap
- name: hopkins
  propername: Johns Hopkins University - Dataverse
  url: http://archive.data.jhu.edu/sitemap.xml
  sourcetype: sitemap
- name: julich
  propername: Forschungszentrum Julich - Dataverse
  url: http://data.fz-juelich.de/sitemap.xml
  sourcetype: sitemap
- name: uva
  propername: University of Virginia (UVA) - Dataverse
  url: http://dataverse.lib.virginia.edu/sitemap.xml
  sourcetype: sitemap
- name: rin
  propername: Repositori Ilmiah Nasional (RIN) - Dataverse
  url: http://data.lipi.go.id/sitemap.xml
  sourcetype: sitemap
- name: lida
  propername: Lithuanian Data Archive for Social Sciences and Humanities (LiDA) - Dataverse
  url: http://lida.dataverse.lt/sitemap.xml
  sourcetype: sitemap
- name: icarda
  propername: International Cente  r for Agricultural Research in Dry Ares (ICARDA) - Dataverse
  url: http://data.mel.cgiar.org/sitemap.xml
  sourcetype: sitemap
- name: nioz
  propername: Royal Netherlands Ins  titute for Sea Research (NIOZ) - Dataverse
  url: http://dataverse.nioz.nl/sitemap.xml
  sourcetype: sitemap
- name: ucdl
  propername: Universite catholique de Louvain - Dataverse
  url: http://dataverse.uclouvain.be/sitemap.xml
  sourcetype: sitemap
- name: ofd
  propername: Open Forest Data - Dataverse
  url: http://dataverse.openforestdata.pl/sitemap.xml
  sourcetype: sitemap
- name: peking
  propername: Peking University - Dataverse
  url: http://opendata.pku.edu.cn/sitemap.xml
  sourcetype: sitemap
- name: pucdp
  propername: Pontificia Universidad Catolica del Peru - Dataverse
  url: http://datos.pucp.edu.pe/sitemap.xml
  sourcetype: sitemap
- name: qdr
  propername: Qualitative Data Repository - Dataverse
  url: http://data.qdr.syr.edu/sitemap.xml
  sourcetype: sitemap
- name: chile
  propername: Repositorio de datos de investigación de la Universidad de Chile - Dataverse
  url: http://datos.uchile.cl/sitemap.xml
  sourcetype: sitemap
- name: rosario
  propername: Repositorio de Datos de Investigación Universidad del Rosario - Dataverse
  url: http://research-data.urosario.edu.co/sitemap.xml
  sourcetype: sitemap
- name: pesquisa
  propername: Repositorios Piloto da Rede Nacional de Ensino e Pesquisa - Dataverse
  url: http://dadosabertos.rnp.br/sitemap.xml
  sourcetype: sitemap
- name: rsu
  propername: Riga Stradins University (RSU) - Dataverse
  url: http://dataverse.rsu.lv/sitemap.xml
  sourcetype: sitemap
- name: tdl
  propername: Texas Data Library (TDL) Repository - Dataverse
  url: http://dataverse.tdl.org/sitemap.xml
  sourcetype: sitemap
- name: ucla
  propername: University of California Los Angeles (UCLA) - Dataverse
  url: http://dataverse.ucla.edu/sitemap.xml
  sourcetype: sitemap
- name: unb
  propername: University of New Brunswick (UNB) Libraries - Dataverse
  url: http://dataverse.lib.unb.ca/sitemap.xml
  sourcetype: sitemap
- name: unc
  propername: University of North Carolina (UNC) - Dataverse
  url: http://dataverse.unc.edu/sitemap.xml
  sourcetype: sitemap
- name: manitoba
  propername: University of Manitoba - Dataverse
  url: http://dataverse.lib.umanitoba.ca/sitemap.xml
  sourcetype: sitemap
- name: milano
  propername: Universita degli Studi di Milano - Dataverse
  url: http://dataverse.unimi.it/sitemap.xml
  sourcetype: sitemap
- name: uwi
  propername: University of the West Indies (UWI) - Dataverse
  url: http://dataverse.sta.uwi.edu/sitemap.xml
  sourcetype: sitemap
- name: vtti
  propername: Virginia Tech Transportation Institute (VTTI) - Dataverse
  url: http://dataverse.vtti.vt.edu/sitemap.xml
  sourcetype: sitemap
- name: wardr
  propername: World Agroforestry Research Data Repository - Dataverse
  url: http://data.worldagroforestry.org/sitemap.xml
  sourcetype: sitemap
- name: yalenus
  propername: Yale-NUS College - Dataverse
  url: http://dataverse.yale-nus.edu.sg/sitemap.xml
  sourcetype: sitemap


