context:
  cache: true
  strict: false
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
gleaner:
  mill: true
  runid: runX
  summon: true
summoner:
    after: ""
    delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
    # will headless, the name of the container "service" work
    headless: http://headless:9222
    #headless: http://localhost:9222
    mode: full
    threads: 5
millers:
  graph: true
minio:
  address:
  port:
  ssl:
  accessKey:
  secretKey:
  bucket:
sources:
  - sourcetype: sitegraph
    name: aquadocs
    logo: ""
    url: https://oih.aquadocs.org/aquadocs.json
    headless: false
    pid: http://hdl.handle.net/1834/41372
    propername: AquaDocs
    domain: https://aquadocs.org
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - sourcetype: sitemap
    name: ecrr_examples
    logo: https://www.earthcube.org/sites/default/files/doc-repository/logo_earthcube_full_horizontal.png
    url: https://earthcube.github.io/ecrro/Examples/sitemap.xml
    headless: false
    pid: http://www.earthcube.org/resourceregistry/examples
    propername: Earthcube Resource Registry Examples
    domain: http://www.earthcube.org/resourceregistry/examples
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifierstring
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json

  - sourcetype: sitemap
    name: geocodes_demo_datasets
    logo: ""
    url: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
    headless: false
    pid: https://github.com/earthcube/GeoCODES-Metadata/metadata/OtherResources
    propername: Geocodes Demo Datasets
    domain: https://www.earthcube.org/datasets/
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - sourcetype: sitemap
    name: geocodes_examples
    logo: ""
    url: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
    headless: false
    pid: https://github.com/earthcube/GeoCODES-Metadata/
    propername: GeoCodes Tools Examples
    domain: https://github.com/earthcube/GeoCODES-Metadata/
    active: true
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifierstring
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json

  - sourcetype: sitemap
    name: iedadata
    logo: https://www.iedadata.org/wp-content/themes/IEDA/assets/img/logo.png
    url: http://get.iedadata.org/doi/xml-sitemap.php
    headless: false
    pid: https://www.re3data.org/repository/r3d100010578
    propername: IEDA (Integrated Earth Data Applications)
    domain: http://www.iedadata.org/
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: $.sameAs
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - sourcetype: sitemap
    name: iris
    logo: http://ds.iris.edu/static/img/layout/logos/iris_logo_shadow.png
    url: http://ds.iris.edu/files/sitemap.xml
    headless: false
    pid: https://www.re3data.org/repository/r3d100010268
    propername: IRIS
    domain: http://iris.edu
    active: true
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json

## HEADLESS EXAMPLE
  - sourcetype: sitemap
    name: magic
    logo: http://mbobak.ncsa.illinois.edu/ext/ec/magic/MagIC.png
    url: https://www2.earthref.org/MagIC/contributions.sitemap.xml
    headless: true
    pid: http://www.re3data.org/repository/r3d100011910
    propername: Magnetics Information Consortium (MagIC)
    domain: https://www.earthref.org/MagIC
    active: false
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: $.sameAs
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - sourcetype: sitemap
    name: geochemistry_custom
    logo:
    url: https://oss.geocodes.ncsa.illinois.edu/decoder/sitemaps/geochemistry_sitemap.xml
    headless: false
    pid: https://catalogue.odis.org/view/343
    propername: Geochemistry Custom Datasets
    domain: https://obis.org
    active: true
    credentialsfile: ""
    other: {}
    headlesswait: -1
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 0
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
