minio:
    address:
    port: 443
    ssl: true
    bucket: ecrr
    region: ""
    accesskey:
    secretkey:
objects:
    bucket: ecrr
    domain: us-east-1
    prefix:
        - summoned/ecrr_submitted
        - summoned/geocodes_examples
        - org
    prefixoff:
        - summoned/ecrr_examples
sparql:
    endpoint: http://localhost/blazegraph/namespace/earthcube/sparql
    authenticate: false
    username: ""
    password: ""
txtaipkg:
    endpoint: http://0.0.0.0:8000
