load_from:
      - python_file:
          relative_path: "project/repositories/repository.py"
          location_name: project
          working_directory: "./project/"
      - python_file:
          relative_path: "workflows/ecrr/repositories/repository.py"
          working_directory: "./workflows/ecrr/"
      # module starting out with the definitions api
      - python_module: "workflows.weekly.weekly"

