minio:
  bucket:
  address:
  port:
  accesskey:
  secretkey:
  ssl: false
context:
    cache: true
    strict: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
sparql:
  endpoint:
  endpointBulk: http://192.168.134.190:9090/blazegraph/namespace/iow/sparql
  endpointMethod: POST
  contentType: text/x-nquads
  authenticate: false
objects:
  domain: us-east-1
  prefix:
    - summoned/counties0


