load_from:
      - python_file:
          relative_path: "project/iow/repositories/repository.py"
          location_name: project
          working_directory: "./project/iow/"
#      - python_file:
#          relative_path: "workflows/ecrr/repositories/repository.py"
#          working_directory: "./workflows/ecrr/"
      # module starting out with the definitions api
      - python_module: "workflows.tasks.tasks"

