# Load-to-triplestore phase.
#
# community_load_files: per tenant/community, generate the artifacts a
#   deployment needs to load that community's subset of the corpus:
#   - tenants/{community}/Qleverfile  (SOURCES + BASE_URL filled in)
#   - tenants/{community}/load.rq     (SPARQL LOAD statements)
# sparql_update_load: for triplestores that accept updates (Blazegraph,
#   Fuseki, ...), POST the source release N-Quads to a configured endpoint.
#   Qlever deployments leave sparql_endpoint unconfigured and reload via
#   container restart instead.
import os
from typing import Any

import requests
from dagster import (
    asset, AssetKey, AssetIn, AssetDep, AllPartitionMapping, Output,
)

from .sources import sources_partitions_def, PREFIX
from .release import release_nquads
from ..paths import RELEASE_PATH, TENANTS_PATH

PROJECT = os.environ.get('PROJECT')

QLEVERFILE_TEMPLATE = """\
# Qleverfile for community: {community}
# Generated by the pysummon pipeline — do not edit by hand.

[data]
NAME          = {community}
SOURCES       = {sources}
BASE_URL      = {base_url}
GET_DATA_CMD  = for source in ${{SOURCES}}; do echo "Downloading ${{source}}..."; curl -fsSLo ${{source}}_release.nq ${{BASE_URL}}/${{source}}_release.nq && echo "  OK: $(wc -l < ${{source}}_release.nq) lines"; done

[index]
INPUT_FILES       = *_release.nq
CAT_INPUT_FILES   = cat ${{INPUT_FILES}}
SETTINGS_JSON     = {{ "add-text-index": true, "ascii-prefixes-only": false, "num-triples-per-batch": 100000 }}

[server]
PORT = 7019
MEMORY_FOR_QUERIES = 10G
"""


def _release_base_url(gs3):
    proto = "https" if gs3.GLEANERIO_MINIO_USE_SSL else "http"
    port = gs3.GLEANERIO_MINIO_PORT
    port_part = "" if port in ("443", "80", "", None) else f":{port}"
    return (f"{proto}://{gs3.GLEANERIO_MINIO_ADDRESS}{port_part}"
            f"/{gs3.GLEANERIO_MINIO_BUCKET}/{RELEASE_PATH}")


@asset(group_name="publish", key_prefix=PREFIX,
       op_tags={"ingest": "report"},
       deps=[AssetDep(AssetKey([PREFIX, "release_nquads"]),
                      partition_mapping=AllPartitionMapping())],
       ins={"tenant_all": AssetIn(AssetKey([PREFIX, "tenant_all"])),
            "sources_names_active": AssetIn(AssetKey([PREFIX, "sources_names_active"]))},
       required_resource_keys={"gs3"})
def community_load_files(context, tenant_all, sources_names_active) -> Output[Any]:
    """Per-community load artifacts: a Qleverfile with the community's source
    subset, and a SPARQL load.rq for update-capable stores."""
    gs3 = context.resources.gs3
    base_url = _release_base_url(gs3)
    written = []
    for tenant in tenant_all["tenant"]:
        community = tenant["community"]
        tenant_sources = tenant.get("sources", [])
        if "all" in tenant_sources:
            tenant_sources = list(sources_names_active)
        else:
            # only sources that are actually active/crawled
            tenant_sources = [s for s in tenant_sources if s in sources_names_active]
        if not tenant_sources:
            context.log.warning(f"tenant {community}: no active sources; skipping")
            continue

        qleverfile = QLEVERFILE_TEMPLATE.format(
            community=community,
            sources=" ".join(tenant_sources),
            base_url=base_url,
        )
        gs3.putTextFile(f"{TENANTS_PATH}/{community}/Qleverfile", qleverfile)

        load_rq = "\n".join(
            f"LOAD <{base_url}/{source}_release.nq> ;" for source in tenant_sources)
        gs3.putTextFile(f"{TENANTS_PATH}/{community}/load.rq", load_rq,
                        content_type="application/sparql-query")
        written.append(community)
        context.log.info(f"tenant {community}: {len(tenant_sources)} sources")

    return Output(written, metadata={
        "communities": written,
        "base_url": base_url,
    })


@asset(group_name="publish", key_prefix=PREFIX,
       op_tags={"tenant_load": "graph"},
       deps=[release_nquads],
       ins={"pipeline_step_config": AssetIn(AssetKey([PREFIX, "pipeline_step_config"]))},
       partitions_def=sources_partitions_def,
       required_resource_keys={"gs3"})
def sparql_update_load(context, pipeline_step_config) -> Output[Any]:
    """POST one source's release N-Quads to a SPARQL endpoint that accepts
    bulk uploads (Blazegraph/Fuseki style).

    Configured in pipelineconfig.yaml:
      defaults:
        sparql_endpoint: https://graph.example.org/blazegraph/namespace/x/sparql
    Skips cleanly when unconfigured (Qlever deployments rebuild from the
    release files instead).
    """
    gs3 = context.resources.gs3
    source = context.asset_partition_key_for_output()
    endpoint = ((pipeline_step_config or {}).get("defaults") or {}).get("sparql_endpoint")
    if not endpoint:
        context.log.info("no sparql_endpoint configured; skipping graph upload")
        return Output(None, metadata={"source": source, "skipped": True})

    release_key = f"{RELEASE_PATH}/{source}_release.nq"
    body = gs3.getFileBytes(release_key)
    if body is None:
        raise Exception(f"release file missing: {release_key}")

    resp = requests.post(endpoint, data=body,
                         headers={"Content-Type": "text/x-nquads"}, timeout=600)
    resp.raise_for_status()
    context.log.info(f"uploaded {release_key} to {endpoint}: {resp.status_code}")
    return Output(endpoint, metadata={
        "source": source,
        "endpoint": endpoint,
        "bytes": len(body),
        "status": resp.status_code,
    })
