# prototype tennants file

# prototype tennants file

tenant:
  - community: dev
    hostname: geocodes-dev
    description: GeoCodes is...
    name: Geocodes Science on Schema
    url: https://www.earthcube.org
    logo: https://unsplash.com/random
    graph:
      main_namespace: test
      summary_namespace: test_summary
    sources:
      - iris
      - opentopography
######
  - community: geocodesall
    hostname: geocodes-all
    description: GeoCodes is...
    name: Geocodes Science on Schema
    url: https://www.earthcube.org
    logo: https://unsplash.com/random
    graph:
      main_namespace: geocodes_test
      summary_namespace: geocodes_test_summary
    sources:
      - all
#  - community: dev4
#    hostname: geocodes-dev32
#    description: GeoCodes is...
#    name: Geocodes Science on Schema
#    url: https://www.earthcube.org
#    logo: https://unsplash.com/random
#    graph:
#      main_namespace: test4
#      summary_namespace: test4_summary
#    sources:
#      - iris
#      - geocodes_examples