name: Dockerize  Dagster
on:
  push:

# https://github.com/marketplace/actions/publish-docker
# https://github.com/docker/build-push-action
defaults:
  run:
    working-directory: .
jobs:
  deploy:
    name: Dockerize  Scheduler for Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "eco" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version:  '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Build package
#        run: python -m build
#      - name: Build tooling
#        run: |
#          cd ./tooling/cfgBuilder/${{ matrix.project }}
#          python cfgBuilder.py -s https://foo.us/sitemap.xml
      - name: Generate
        run: |
            python pygen.py -cf ./configs/${{ matrix.project }}/gleanerconfig.yaml -od ./generatedCode/implnet-${{ matrix.project }}/output  -td ./templates/v1   -d 7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nsfearthcube/dagster-${{ matrix.project }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./build/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
#          tags: nsfearthcube/ec_facets_client:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
